/**
 * hospital_appointment - React Native Entry Point
 *
 * Generated by UmitUZ App Factory
 * Category: health_wellness
 * Theme: {{THEME}}
 */

import { registerRootComponent } from 'expo';
import App from './App';

// Register the root component for Expo
registerRootComponent(App);